// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RpgApi.Infrastructure.Persistence;

#nullable disable

namespace RpgApi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RpgDbContext))]
    [Migration("20260509120852_FixSnapshot")]
    partial class FixSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RpgApi.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<int>("CurrentHealth")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("MaxHealth")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Class");

                    b.HasIndex("Name");

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("RpgApi.Domain.Entities.CharacterItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEquipped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("CharacterId", "ItemId")
                        .IsUnique();

                    b.ToTable("CharacterItems", (string)null);
                });

            modelBuilder.Entity("RpgApi.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AgilityBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DefenseBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IntelligenceBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StrengthBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.ToTable("Items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            AgilityBonus = 0,
                            DefenseBonus = 0,
                            Description = "Ett vanligt järnsvärd.",
                            IntelligenceBonus = 0,
                            Name = "Järnsvärd",
                            StrengthBonus = 5,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            AgilityBonus = 0,
                            DefenseBonus = 0,
                            Description = "En stav laddad med magisk energi.",
                            IntelligenceBonus = 8,
                            Name = "Trollstav",
                            StrengthBonus = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            AgilityBonus = 2,
                            DefenseBonus = 5,
                            Description = "Lätt rustning som inte hämmar rörelseförmågan.",
                            IntelligenceBonus = 0,
                            Name = "Läderharnesk",
                            StrengthBonus = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            AgilityBonus = 0,
                            DefenseBonus = 12,
                            Description = "Tung och skyddande stålrustning.",
                            IntelligenceBonus = 0,
                            Name = "Plåtrustning",
                            StrengthBonus = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            AgilityBonus = 0,
                            DefenseBonus = 0,
                            Description = "Återställer 50 hälsopoäng.",
                            IntelligenceBonus = 0,
                            Name = "Helbredelsedryck",
                            StrengthBonus = 0,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000006"),
                            AgilityBonus = 0,
                            DefenseBonus = 0,
                            Description = "Ger +10 styrka i 1 timme.",
                            IntelligenceBonus = 0,
                            Name = "Styrkedryck",
                            StrengthBonus = 10,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000007"),
                            AgilityBonus = 4,
                            DefenseBonus = 0,
                            Description = "En lätt dolk perfekt för lönnmördare.",
                            IntelligenceBonus = 0,
                            Name = "Smygdolk",
                            StrengthBonus = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000008"),
                            AgilityBonus = 0,
                            DefenseBonus = 0,
                            Description = "Ökar bärarens intelligens.",
                            IntelligenceBonus = 6,
                            Name = "Visdomsamulett",
                            StrengthBonus = 0,
                            Type = 4
                        });
                });

            modelBuilder.Entity("RpgApi.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("RpgApi.Domain.Entities.CharacterItem", b =>
                {
                    b.HasOne("RpgApi.Domain.Entities.Character", "Character")
                        .WithMany("Inventory")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RpgApi.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("RpgApi.Domain.Entities.Character", b =>
                {
                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
